src/main/java/de/othr/sw/banklutz/entity/Transfer.java
package de.othr.sw.banklutz.entity;

import de.othr.sw.banklutz.entity.util.SingleIdEntity;
import de.othr.sw.banklutz.exception.CreditOutOfLimitException;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Min;
import javax.xml.bind.annotation.XmlType;

@Entity
@XmlType(namespace="de.othr.sw.banklutz.entity")
public class Transfer extends SingleIdEntity<Long> implements Serializable {
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    
    @ManyToOne
    private Account sender;
    
    @ManyToOne
    private Account reciever;
    
    @Min(1)
    private int amount;
    
    @Temporal(value=TemporalType.TIMESTAMP)
    private Date time = new Date();
    
    public Transfer() {
        
    }
    
    public Transfer(Account sender, Account reciever, int amount) throws CreditOutOfLimitException {
        this.sender = sender;
        this.reciever = reciever;
        this.amount = amount;
        
        exchange();
    }
    
    private void exchange() throws CreditOutOfLimitException {
        sender.reduceCredits(amount);
        reciever.addCredits(amount);
    }

    @Override
    public Long getId() {
        return id;
    }

    public Account getSender() {
        return sender;
    }
    
    public void setSender(Account sender) {
        this.sender = sender;
    }

    public Account getReciever() {
        return reciever;
    }
    
    public void setReciever(Account reciever) {
        this.reciever = reciever;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public Date getTime() {
        return time;
    }
}

src/main/java/de/othr/sw/banklutz/model/CashTerminalModel.java
package de.othr.sw.banklutz.model;

import de.othr.sw.banklutz.annotation.CustomerBean;
import de.othr.sw.banklutz.entity.Account;
import de.othr.sw.banklutz.entity.CashTerminal;
import de.othr.sw.banklutz.entity.converter.CashTerminalConverter;
import de.othr.sw.banklutz.exception.CreditOutOfLimitException;
import de.othr.sw.banklutz.service.AccountService;
import de.othr.sw.banklutz.service.CashTerminalService;
import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@SessionScoped
public class CashTerminalModel implements Serializable {  
    @Inject
    private CashTerminalService terminalService;
    
    @Inject
    private AccountService accountService;
    
    @Inject @CustomerBean
    private CustomerModel customerModel;
    
    @Inject
    private Error error;
    
    @Inject
    private CashTerminalConverter cashTerminalConverter;
    
    private long accountId;
    private int pin;
    private int lowAmount;
    private int highAmount;
    private int amount;
    private int storedCash;
    private String name;
    
    private CashTerminal terminal;
    
    private CashTerminal targetTerminal;
    
    public String deposit() {
        Account account = accountService.getAccountById(accountId);
        
        amount = (highAmount * 100) + lowAmount;
        
        if(checkPin(account, pin)) {
            try {
                terminalService.deposit(terminal, account, amount);
                customerModel.updateCurrentUser();
            } catch (CreditOutOfLimitException ex) {
                error.addError("Einzahlung nicht erfolgreich. Guthaben im Automaten nicht ausreichend.");
                return "";
            }
            
            return "overview";
        }
        
        return "";
    }
    
    public String withdraw() {
        Account account = accountService.getAccountById(accountId);
        
        amount = (highAmount * 100) + lowAmount;
        
        if(checkPin(account, pin)) {
            try {
                terminalService.withdraw(terminal, account, amount);
                customerModel.updateCurrentUser();
            } catch (CreditOutOfLimitException ex) {
                error.addError("Auszahlung nicht erfolgreich. Guthaben im Konto nicht ausreichend.");
                return "";
            }
            
            return "overview";
        }
        
        return "";
    }
    
    public String create() {
        CashTerminal terminal = new CashTerminal(name, storedCash);
        
        terminalService.createCashTerminal(terminal);
        
        return "overview";
    }
    
    public String edit(Long id) {
        targetTerminal = terminalService.getTerminalById(id);
        return "edit";
    }
    
    public String update() {
        if(targetTerminal != null) {
            terminalService.updateCashTerminal(targetTerminal);
            targetTerminal = null;
        }
        
        return "overview";
    }
    
    public String delete(Long id) {
        CashTerminal terminal = terminalService.getTerminalById(id);
        
        if(terminal != null)
            terminalService.deleteCashTerminal(terminal);
        
        return "overview";
    }

    public List<CashTerminal> getTerminals() {
        return terminalService.getAllTerminals();
    }
    
    public List<Account> getCustomerAccounts() {
        return customerModel.getUserInSession().getAccounts();
    }

    public long getAccountId() {
        return accountId;
    }

    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }

    public int getPin() {
        return pin;
    }

    public void setPin(int pin) {
        this.pin = pin;
    }

    public int getLowAmount() {
        return lowAmount;
    }

    public void setLowAmount(int lowAmount) {
        this.lowAmount = lowAmount;
    }

    public int getHighAmount() {
        return highAmount;
    }

    public void setHighAmount(int highAmount) {
        this.highAmount = highAmount;
    }

    public int getStoredCash() {
        return storedCash;
    }

    public void setStoredCash(int storedCash) {
        this.storedCash = storedCash;
    }

    public CashTerminal getTerminal() {
        return terminal;
    }

    public void setTerminal(CashTerminal terminal) {
        this.terminal = terminal;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CashTerminal getTargetTerminal() {
        return targetTerminal;
    }
    
    private boolean checkPin(Account account, int pin) {
        return accountService.checkPin(account, pin);
    }

    public CashTerminalConverter getCashTerminalConverter() {
        return cashTerminalConverter;
    }
    
}

src/main/webapp/dashboard/transfer/overview.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="/templates/dashboard.xhtml">
    <ui:define name="content">
        <b:form inline="true">
                <b:row>
                    <div class="col-md-6 col-xs-12 col-sm-8 col-lg-5">
                        <div class="form-group">
                            <h:outputLabel style="width: 150px">Konto</h:outputLabel>
                            <h:selectOneMenu value="#{transferModel.selectedAccount}">
                                <f:converter binding="#{transferModel.accountConverter}" />
                                <f:selectItems value="#{transferModel.customerAccounts}" />
                            </h:selectOneMenu>
                            <b:commandButton value="auswählen" action="#{transferModel.selectAccount()}" style="margin-left: 15px" />
                        </div>
                    </div>
                </b:row>
        </b:form>
        <b:row>
            <div class="col-md-6 col-xs-12 col-sm-8 col-lg-5">
                <h:outputLabel>Aktuelles Konto: #{(transferModel.selectedAccount != null) ? transferModel.selectedAccount : "Kein"}</h:outputLabel>
            </div>
        </b:row>
        <b:dataTable value="#{transferModel.transfers}" var="transfer" lang="de">
            <b:dataTableColumn value="#{transfer.sender.id}" label="Sender" />
            <b:dataTableColumn value="#{transfer.reciever.id}" label="Empfänger" />
            <b:dataTableColumn value="#{transfer.amount}" label="Wert in Cent" />
            <b:dataTableColumn value="#{transfer.time}" label="Datum"  order="desc"/>
        </b:dataTable>
    </ui:define>
</ui:composition>

src/main/webapp/dashboard/transfer/transfer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="/templates/dashboard.xhtml">
    <ui:define name="content">
        <b:panel title="Überweisung" collapsible="false" look="primary">
            <b:form inline="true">
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Sender-Kontonr." render-label="true" label-style="width:150px"
                         value="#{transferModel.senderId}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Empfänger-Kontonr." render-label="true" label-style="width:150px"
                         value="#{transferModel.recieverId}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Euro" render-label="true" label-style="width:150px"
                         value="#{transferModel.highAmount}" span="2" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Cent" render-label="true" label-style="width:150px"
                         value="#{transferModel.lowAmount}" span="2" />
                </b:row>
                <b:row>
                    <b:commandButton value="Überweisen" action="#{transferModel.transfer()}" style="margin-left: 15px" />
                </b:row>
            </b:form>
        </b:panel>
    </ui:define>
</ui:composition>