src/main/java/de/othr/sw/banklutz/entity/Customer.java
package de.othr.sw.banklutz.entity;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

@Entity
public class Customer extends User {
    @OneToMany(cascade=CascadeType.REMOVE, mappedBy="customer", targetEntity=Account.class, fetch = FetchType.EAGER)
    private List<Account> accounts;
    
    public Customer() {
        super();
        accounts = new ArrayList<>();
    }
    
    public Customer(String email, String password) {
        super(email, password);
        accounts = new ArrayList<>();
    }

    public void addAccount(Account account) {
        if(account != null) {
            if(!accounts.contains(account)) {
                accounts.add(account);
                if(account.getCustomer() == null) 
                    account.setCustomer(this);
            }        
        } 
    }
    
    public void removeAccount(Account account) {
        if(account != null) {
            if(accounts.contains(account)) {
                accounts.remove(account);  
                if(account.getCustomer() != null) {
                    account.setCustomer(null);
                }
            }     
        } 
    }
    
    public List<Account> getModifiableAccounts() {           
        return accounts;
    }
    
    public List<Account> getAccounts() {
        return Collections.unmodifiableList(accounts);
    }
}

src/main/java/de/othr/sw/banklutz/entity/util/SingleIdEntity.java
package de.othr.sw.banklutz.entity.util;

import java.util.Objects;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class SingleIdEntity<PK> {
    public abstract PK getId();
    
    @Override
    public boolean equals(Object other) {
        if(other instanceof SingleIdEntity)
            return Objects.equals(this.getId(), ((SingleIdEntity)other).getId());
        else
            return false;
    }
    
    @Override
    public int hashCode() {
        return Objects.hashCode(this.getId());
    }
}

src/main/java/de/othr/sw/banklutz/annotation/CustomerBean.java
package de.othr.sw.banklutz.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.inject.Qualifier;

@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE})
public @interface CustomerBean { }

src/main/webapp/employee/user_management/customer/edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="/templates/employee.xhtml">
    <ui:define name="content">
        <b:panel title="#{customerModel.targetCustomer.id} bearbeiten" collapsible="false" look="primary">
            <b:form inline="true">
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Vorname" render-label="true" label-style="width:150px"
                         value="#{customerModel.targetCustomer.name}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Nachname" render-label="true" label-style="width:150px"
                         value="#{customerModel.targetCustomer.lastName}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Straße" render-label="true" label-style="width:150px"
                         value="#{customerModel.targetCustomer.address.street}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Postleitzahl" render-label="true" label-style="width:150px"
                         value="#{customerModel.targetCustomer.address.postcode}" />
                </b:row>
                <b:row>
                    <b:inputText tiny-screen="12" small-screen="8" medium-screen="6" large-screen="5" label="Ort" render-label="true" label-style="width:150px"
                         value="#{customerModel.targetCustomer.address.place}" />
                </b:row>
                <b:row>
                    <b:commandButton value="Bearbeiten" action="#{customerModel.update()}" style="margin-left: 15px" />
                </b:row>
            </b:form>
        </b:panel>
    </ui:define>
</ui:composition>

src/main/webapp/employee/user_management/customer/overview.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:b="http://bootsfaces.net/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="/templates/employee.xhtml">
    <ui:define name="content">
        <b:dataTable value="#{customerModel.getAllCustomers()}" var="customer" lang="de">
            <b:dataTableColumn value="#{customer.id}" label="E-Mail" order="asc" />
            <b:dataTableColumn value="#{customer.name}" label="Vorname" />
            <b:dataTableColumn value="#{customer.lastName}" label="Nachname" />
            <b:dataTableColumn value="#{customer.accounts.size()}" label="Konten" />
            <b:dataTableColumn label="">
                <b:form>
                    <b:buttonGroup>
                        <b:commandButton value="bearbeiten" icon="edit" size="xs" action="#{customerModel.edit(customer.id)}" />
                        <b:commandButton value="löschen" icon="remove" size="xs" action="#{customerModel.delete(customer.id)}" look="danger" onclick="return confirm('Wirklich löschen?')" />
                    </b:buttonGroup>
                </b:form>
           </b:dataTableColumn>
        </b:dataTable>
    </ui:define>
</ui:composition>